---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonAnnotations:
#   argocd.argoproj.io/sync-wave: "25"

commonLabels:
  operator: compliance

resources:
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml
